part of '../../models.dart';

///
class Assets implements Model {
  /// The asset family this asset belongs to — which attributes it carries and how its file is named. A create falls back to the `default_asset_family` tenant setting when the body names none.
  final String? asset_family_id;

  /// Every attribute value the record carries, in ONE jsonb document — the core of an attribute-driven PIM. A record's properties are not columns here: they are rows in `attributes`, selected per family by `family_attributes`, and their values live under their attribute CODE inside this object.
  ///
  /// Four buckets, and an attribute's own flags decide which one it writes to:
  ///
  ///   `common`                    the attribute is neither localizable nor scopable — one value, full stop.
  ///                               `{"common": {"net_weight": 2.4, "colour": "black"}}`
  ///   `locale_specific`           `localizable`: one value per language tag.
  ///                               `{"locale_specific": {"de_DE": {"name": "Akku-Bohrschrauber"}}}`
  ///   `channel_specific`          `scopable`: one value per channel.
  ///                               `{"channel_specific": {"b2b": {"minimum_order_quantity": 6}}}`
  ///   `channel_locale_specific`   both: one value per channel AND language tag.
  ///                               `{"channel_locale_specific": {"b2b": {"de_DE": {"description": "…"}}}}`
  ///
  /// A reader takes the most specific bucket that carries the code and falls back through locale, then channel, then `common`. `common` is always last and always consulted, because early imports wrote everything there whatever an attribute's flags said — a reader that skipped it reports an imported catalog as empty. `GET /products/attribute-schema` answers, per field, the exact path a value belongs at (`storage.path`) and that full fallback order (`from`), so no client has to re-derive any of this.
  ///
  /// The value itself is whatever the attribute's `type` implies: a string, a number, a boolean, an option CODE for a select (never its label), a list of codes for a multi-select, `{"amount": …, "unit": …}` for a measure, a list of `{"amount": …, "currency": …}` for a price, an asset code for media.
  ///
  /// Defaults to `{}`, and an empty object is a normal state — a record nobody has enriched yet. The declared type also admits an array only because every jsonb column of this app shares one mapping; an array is not meaningful here and every reader in this app treats a non-object as empty.
  ///
  /// Which attributes an asset of this family has comes from `attributes` rows with `entity_type: "asset"` and `entity_ref` equal to the family's code — alt text, copyright, an expiry date.
  final Map? attribute_values;

  /// The asset's stable identifier within its family — the value a product's media attribute stores. Unique per family.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The path the CDN serves this asset under — the convenient value for rendering. It changes when the file is moved, so never join on it.
  final String? delivery_path;

  /// Absolute URL of an externally hosted file. Required when `source` is `external`, and accepted only when the tenant has `allow_external_media` on and the host is on its `external_media_allowed_hosts` list — `POST /products/assets` is the only place an external URL can enter the catalog, so it is the only place those are enforced.
  final String? external_url;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// Where the bytes live: 'storage' is this platform's object store and needs `storage_asset_id`, 'external' is somebody else's host and needs `external_url`. The database enforces the pair, so neither half can be stored on its own.
  final String? source;

  /// The stable `ast_…` id of the storage object. It survives a rename or a folder move, which is exactly why it and not the delivery path is the identifier. Required when `source` is `storage`.
  final String? storage_asset_id;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  Assets({
    this.asset_family_id,
    this.attribute_values,
    this.code,
    this.created_at,
    this.delivery_path,
    this.external_url,
    this.id,
    this.source,
    this.storage_asset_id,
    this.updated_at,
  });

  factory Assets.fromMap(Map<String, dynamic> map) {
    return Assets(
      asset_family_id: map['asset_family_id']?.toString(),
      attribute_values: map['attribute_values'],
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      delivery_path: map['delivery_path']?.toString(),
      external_url: map['external_url']?.toString(),
      id: map['id']?.toString(),
      source: map['source']?.toString(),
      storage_asset_id: map['storage_asset_id']?.toString(),
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "asset_family_id": asset_family_id,
      "attribute_values": attribute_values,
      "code": code,
      "created_at": created_at,
      "delivery_path": delivery_path,
      "external_url": external_url,
      "id": id,
      "source": source,
      "storage_asset_id": storage_asset_id,
      "updated_at": updated_at,
    };
  }
}
