part of '../../models.dart';

///
class AssetFamilies implements Model {
  /// The asset family's stable identifier — a class of media with one shared shape. Unique per tenant.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// What the asset family is called, per language tag.
  final Map? labels;

  /// How a file of this family is named, so an import can bind a file to a product without a mapping table. `source` is the product value the file name is built from, `pattern` how it is assembled, `allowed_extensions` what may be uploaded.
  final Map? naming_convention;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  AssetFamilies({
    this.code,
    this.created_at,
    this.id,
    this.labels,
    this.naming_convention,
    this.updated_at,
  });

  factory AssetFamilies.fromMap(Map<String, dynamic> map) {
    return AssetFamilies(
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      id: map['id']?.toString(),
      labels: map['labels'],
      naming_convention: map['naming_convention'],
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "code": code,
      "created_at": created_at,
      "id": id,
      "labels": labels,
      "naming_convention": naming_convention,
      "updated_at": updated_at,
    };
  }
}
