part of '../../models.dart';

/// 
class AssociationTypes implements Model {
    /// The kind of relation between two products. Unique per tenant.
    final String? code;

    /// When the row was created. Server-set — it is not part of any request body.
    final String? created_at;

    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    final String? id;

    /// Declares that a relation of this kind carries a quantity — a bundle, a bill of materials. `product_associations.quantity` is where that number goes, and it is meaningless without this flag.
    final bool? is_quantified;

    /// Declares the relation symmetric — an accessory of A is an accessory of B. It is a declaration a client reads: this app stores one row per direction and does not create the mirror for you.
    final bool? is_two_way;

    /// What the relation is called in a product form, per language tag.
    final Map? labels;

    AssociationTypes({
        this.code,
        this.created_at,
        this.id,
        this.is_quantified,
        this.is_two_way,
        this.labels,
    });

    factory AssociationTypes.fromMap(Map<String, dynamic> map) {
        return AssociationTypes(
            code: map['code']?.toString(),
            created_at: map['created_at']?.toString(),
            id: map['id']?.toString(),
            is_quantified: map['is_quantified'],
            is_two_way: map['is_two_way'],
            labels: map['labels'],
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "code": code,
            "created_at": created_at,
            "id": id,
            "is_quantified": is_quantified,
            "is_two_way": is_two_way,
            "labels": labels,
        };
    }
}
