part of '../../models.dart';

///
class AttributeGroups implements Model {
  /// The group's stable identifier, and the value an `AttributeField` carries as its `group` — a SECTION of the product form, not a label. Unique per tenant and the key an import joins on.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// The section heading a person sees, keyed by language tag. The code is never shown to an operator; a tag nobody translated falls back to the next filled one, then to English.
  final Map? labels;

  /// Where this section sits in a form, ascending. Sections that tie keep the order the database returns them in.
  final int? position;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  AttributeGroups({
    this.code,
    this.created_at,
    this.id,
    this.labels,
    this.position,
    this.updated_at,
  });

  factory AttributeGroups.fromMap(Map<String, dynamic> map) {
    return AttributeGroups(
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      id: map['id']?.toString(),
      labels: map['labels'],
      position: map['position'],
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "code": code,
      "created_at": created_at,
      "id": id,
      "labels": labels,
      "position": position,
      "updated_at": updated_at,
    };
  }
}
