part of '../../models.dart';

///
class AttributeOptions implements Model {
  /// The select / multi-select attribute these are the permitted values of. Deleting the attribute deletes its options with it.
  final String? attribute_id;

  /// The value actually STORED in a record's `attribute_values` when this option is picked — never the label. Unique within the attribute.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// What the option is called, per language tag. Two tenants may label the same code differently; only the code is ever written into a record.
  final Map? labels;

  /// Order in the dropdown, ascending. Options that tie keep the order the database returns them in, so give every option a position if the order matters.
  final int? position;

  /// A colour or texture chip for the picker. Null for an option that is not visual.
  final Map? swatch;

  AttributeOptions({
    this.attribute_id,
    this.code,
    this.created_at,
    this.id,
    this.labels,
    this.position,
    this.swatch,
  });

  factory AttributeOptions.fromMap(Map<String, dynamic> map) {
    return AttributeOptions(
      attribute_id: map['attribute_id']?.toString(),
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      id: map['id']?.toString(),
      labels: map['labels'],
      position: map['position'],
      swatch: map['swatch'],
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "attribute_id": attribute_id,
      "code": code,
      "created_at": created_at,
      "id": id,
      "labels": labels,
      "position": position,
      "swatch": swatch,
    };
  }
}
