part of '../../models.dart';

/// 
class Categories implements Model {
    /// The category's stable identifier — what an import and a storefront join on, and what survives a rename of the label. Unique per tenant.
    final String? code;

    /// When the row was created. Server-set — it is not part of any request body.
    final String? created_at;

    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    final String? id;

    /// The category name a person sees, per language tag. The catalog reads by name, not by code — a locale left blank falls back to the next filled one.
    final Map? labels;

    /// The category this one hangs under. Null is a root of the tree. Deleting a parent lifts its children to the root rather than deleting them, so a mis-click never takes a subtree with it.
    final String? parent_id;

    /// A materialized position in the tree, kept for importers that carry one (`tools/power_tools/cordless_drills`). Nothing in this app writes or reads it — `parent_id` is the structure this app navigates.
    final String? path;

    /// Order among the siblings under the same parent, ascending.
    final int? position;

    /// How the conditions combine: 'all' ANDs them (the default), 'any' ORs them. It is a column of its own rather than a key of `rules` because the compiler reads the two separately.
    final String? rule_match;

    /// The selector that makes this a RULE-DRIVEN category. Null means hand-picked. Matching products are MATERIALIZED as `product_categories` rows with source `rule`, next to the hand-picked ones a recompute never touches; `POST /products/categories/{category_id}/rules/preview` dry-runs this exact document before it is stored. Conditions address the `common` bucket of a product's values — a value held per locale or per channel has no single answer for a rule to test.
    final Map? rules;

    /// When the rule last ran TO COMPLETION and its memberships were synced. Null means no pass has ever finished — a recompute is chunked, so a half-finished pass leaves this untouched.
    final String? rules_computed_at;

    /// When the row was last written. Server-set — it is not part of any request body.
    final String? updated_at;

    /// Whatever this catalog keeps on a category beyond the model — the keys belong to the tenant, not to this app, and nothing here reads them.
    final Map? values;

    Categories({
        this.code,
        this.created_at,
        this.id,
        this.labels,
        this.parent_id,
        this.path,
        this.position,
        this.rule_match,
        this.rules,
        this.rules_computed_at,
        this.updated_at,
        this.values,
    });

    factory Categories.fromMap(Map<String, dynamic> map) {
        return Categories(
            code: map['code']?.toString(),
            created_at: map['created_at']?.toString(),
            id: map['id']?.toString(),
            labels: map['labels'],
            parent_id: map['parent_id']?.toString(),
            path: map['path']?.toString(),
            position: map['position'],
            rule_match: map['rule_match']?.toString(),
            rules: map['rules'],
            rules_computed_at: map['rules_computed_at']?.toString(),
            updated_at: map['updated_at']?.toString(),
            values: map['values'],
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "code": code,
            "created_at": created_at,
            "id": id,
            "labels": labels,
            "parent_id": parent_id,
            "path": path,
            "position": position,
            "rule_match": rule_match,
            "rules": rules,
            "rules_computed_at": rules_computed_at,
            "updated_at": updated_at,
            "values": values,
        };
    }
}
