part of '../../models.dart';

/// 
class Families implements Model {
    /// The family's stable identifier — which set of attributes a product of this family HAS. Unique per tenant, and the value `GET /products/attribute-schema?family_code=` resolves.
    final String? code;

    /// When the row was created. Server-set — it is not part of any request body.
    final String? created_at;

    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    final String? id;

    /// Which attribute code carries the product's main image — the one a grid thumbnail and a picker read.
    final String? image_attribute;

    /// Which attribute CODE carries the display name of a product in this family. A product's name is an attribute, not a column, and which attribute it is, is per family. Null falls back to the `default_label_attribute` setting and then to the conventional `name`.
    final String? label_attribute;

    /// What the family is called, per language tag — the name an operator picks from, while the code is what everything else joins on.
    final Map? labels;

    /// When the row was last written. Server-set — it is not part of any request body.
    final String? updated_at;

    Families({
        this.code,
        this.created_at,
        this.id,
        this.image_attribute,
        this.label_attribute,
        this.labels,
        this.updated_at,
    });

    factory Families.fromMap(Map<String, dynamic> map) {
        return Families(
            code: map['code']?.toString(),
            created_at: map['created_at']?.toString(),
            id: map['id']?.toString(),
            image_attribute: map['image_attribute']?.toString(),
            label_attribute: map['label_attribute']?.toString(),
            labels: map['labels'],
            updated_at: map['updated_at']?.toString(),
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "code": code,
            "created_at": created_at,
            "id": id,
            "image_attribute": image_attribute,
            "label_attribute": label_attribute,
            "labels": labels,
            "updated_at": updated_at,
        };
    }
}
