part of '../../models.dart';

///
class FamilyVariants implements Model {
  /// The attribute codes a product model splits its variants on. Two shapes are in the wild and both are read: a bare list of codes, or one entry per level, outermost first — `[{"level": 1, "axes": ["colour"]}, {"level": 2, "axes": ["size"]}]`. An attribute named here is READ-ONLY on the model and set on each variant, which is what `AttributeField.readonly_reason` reports.
  final Map? axes;

  /// The variant structure's stable identifier — how this family splits, not which product it splits. Unique per tenant.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The family this variant structure belongs to. A family may carry several, and a product names the one it follows through `family_variant_id`.
  final String? family_id;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// What the variant structure is called, per language tag.
  final Map? labels;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  FamilyVariants({
    this.axes,
    this.code,
    this.created_at,
    this.family_id,
    this.id,
    this.labels,
    this.updated_at,
  });

  factory FamilyVariants.fromMap(Map<String, dynamic> map) {
    return FamilyVariants(
      axes: map['axes'],
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      family_id: map['family_id']?.toString(),
      id: map['id']?.toString(),
      labels: map['labels'],
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "axes": axes,
      "code": code,
      "created_at": created_at,
      "family_id": family_id,
      "id": id,
      "labels": labels,
      "updated_at": updated_at,
    };
  }
}
