part of '../../models.dart';

///
class MeasurementFamilies implements Model {
  /// The measurement family's stable identifier. A `measure` attribute names one and then offers that family's units.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// What the measurement family is called, per language tag.
  final Map? labels;

  /// The unit every value of this family is converted to before it is compared or sorted — the unit each `convert_factor` is relative to.
  final String? standard_unit;

  /// The units this family offers. `convert_factor` multiplies a value into `standard_unit`, so a gram is 0.001 kilograms; `symbol` is what a form prints next to the number.
  final Map? units;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  MeasurementFamilies({
    this.code,
    this.created_at,
    this.id,
    this.labels,
    this.standard_unit,
    this.units,
    this.updated_at,
  });

  factory MeasurementFamilies.fromMap(Map<String, dynamic> map) {
    return MeasurementFamilies(
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      id: map['id']?.toString(),
      labels: map['labels'],
      standard_unit: map['standard_unit']?.toString(),
      units: map['units'],
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "code": code,
      "created_at": created_at,
      "id": id,
      "labels": labels,
      "standard_unit": standard_unit,
      "units": units,
      "updated_at": updated_at,
    };
  }
}
