part of '../../models.dart';

/// 
class OrderListKindRow implements Model {
    /// What `lists.kind` stores. Lowercase, immutable once created — renaming it would orphan every list that carries it, so a merchant who wants a different code creates a new kind and moves the lists over.
    final String? code;

    /// When the kind was created — the install for a seeded one.
    final String? created_at;

    /// What this kind is FOR, in the tenant's own words — the sentence a select shows underneath the title. `descriptions` carries the localized forms. Same caveat as `title`: a kind seeded before 0.15.0 may hold a serialized locale map here (PE-450).
    final String? description;

    /// Localized descriptions, keyed by language tag. Same fallback as `labels`: `description` is what a reader gets when their tag is missing.
    final Map<String, dynamic>? descriptions;

    /// The kind, by id. Generated by the database and what every /orderlists/kinds/{id} route addresses — the `code` is the identity a LIST carries, the id is the identity a route takes.
    final String? id;

    /// The kind a list created without one gets. Exactly one row carries it — promoting a kind demotes the previous holder — and the market-scoped `default_kind` setting still wins where a tenant set it.
    final bool? is_default;

    /// Seeded on install rather than created by the merchant. It changes nothing about what may be done to the row: a system kind is still renameable, still retirable, and still deletable once no list carries it.
    final bool? is_system;

    /// Localized titles, keyed by language tag. `title` is what a reader gets when their tag is missing, so this only ever adds languages — it never replaces the plain one.
    final Map<String, dynamic>? labels;

    /// Where this kind sits in a select, ascending. Ties fall back to the code, so the order is stable.
    final int? position;

    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    final String? tenant_id;

    /// What a person reads, in the tenant's own words. `labels` carries the localized forms. Kinds seeded before 0.15.0 hold a serialized locale map here instead — the seed wrote its `{en, de}` map into this `text` column and left `labels` null, and Postgres stores such a map as its JSON text rather than refusing it (PE-450). Those rows are not repaired by the fix; a repair is a data change.
    final String? title;

    /// Semantic badge colour. The client owns what each tone looks like; the kind only says what the value MEANS.
    final enums.OrderListKindRowTone? tone;

    /// When the kind was last written.
    final String? updated_at;

    OrderListKindRow({
        this.code,
        this.created_at,
        this.description,
        this.descriptions,
        this.id,
        this.is_default,
        this.is_system,
        this.labels,
        this.position,
        this.tenant_id,
        this.title,
        this.tone,
        this.updated_at,
    });

    factory OrderListKindRow.fromMap(Map<String, dynamic> map) {
        return OrderListKindRow(
            code: map['code']?.toString(),
            created_at: map['created_at']?.toString(),
            description: map['description']?.toString(),
            descriptions: map['descriptions'],
            id: map['id']?.toString(),
            is_default: map['is_default'],
            is_system: map['is_system'],
            labels: map['labels'],
            position: map['position'],
            tenant_id: map['tenant_id']?.toString(),
            title: map['title']?.toString(),
            tone: map['tone'] != null ? enums.OrderListKindRowTone.values.firstWhere((e) => e.value == map['tone']) : null,
            updated_at: map['updated_at']?.toString(),
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "code": code,
            "created_at": created_at,
            "description": description,
            "descriptions": descriptions,
            "id": id,
            "is_default": is_default,
            "is_system": is_system,
            "labels": labels,
            "position": position,
            "tenant_id": tenant_id,
            "title": title,
            "tone": tone?.value,
            "updated_at": updated_at,
        };
    }
}
