part of '../../models.dart';

/// 
class ProductCategories implements Model {
    /// The category it is filed into. One row per (product, category), whichever way it got there.
    final String? category_id;

    /// When the row was created. Server-set — it is not part of any request body.
    final String? created_at;

    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    final String? id;

    /// Sort order of this product inside the category.
    final int? position;

    /// The product filed into the category. Deleting the product deletes the membership with it.
    final String? product_id;

    /// How the membership came about: 'manual' is hand-picked, 'rule' was materialized by a category rule. The two never touch each other — a recompute only ever inserts and deletes `rule` rows, so a hand-picked membership survives every pass.
    final String? source;

    ProductCategories({
        this.category_id,
        this.created_at,
        this.id,
        this.position,
        this.product_id,
        this.source,
    });

    factory ProductCategories.fromMap(Map<String, dynamic> map) {
        return ProductCategories(
            category_id: map['category_id']?.toString(),
            created_at: map['created_at']?.toString(),
            id: map['id']?.toString(),
            position: map['position'],
            product_id: map['product_id']?.toString(),
            source: map['source']?.toString(),
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "category_id": category_id,
            "created_at": created_at,
            "id": id,
            "position": position,
            "product_id": product_id,
            "source": source,
        };
    }
}
