part of '../../models.dart';

/// 
class ProductAssociations implements Model {
    /// Which kind of relation this is — the `association_types` row.
    final String? association_type_id;

    /// When the row was created. Server-set — it is not part of any request body.
    final String? created_at;

    /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
    final String? id;

    /// Order in which the targets are shown, ascending.
    final int? position;

    /// The product the relation starts at — the one whose detail page shows it.
    final String? product_id;

    /// How many of the target belong to the source — the 4 in "this bundle contains 4 casters". Only meaningful when the association type carries `is_quantified`; null on an ordinary cross-sell.
    final double? quantity;

    /// The product the relation points at — the accessory, the spare part, the cross-sell.
    final String? target_product_id;

    ProductAssociations({
        this.association_type_id,
        this.created_at,
        this.id,
        this.position,
        this.product_id,
        this.quantity,
        this.target_product_id,
    });

    factory ProductAssociations.fromMap(Map<String, dynamic> map) {
        return ProductAssociations(
            association_type_id: map['association_type_id']?.toString(),
            created_at: map['created_at']?.toString(),
            id: map['id']?.toString(),
            position: map['position'],
            product_id: map['product_id']?.toString(),
            quantity: map['quantity']?.toDouble(),
            target_product_id: map['target_product_id']?.toString(),
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "association_type_id": association_type_id,
            "created_at": created_at,
            "id": id,
            "position": position,
            "product_id": product_id,
            "quantity": quantity,
            "target_product_id": target_product_id,
        };
    }
}
