part of '../../models.dart';

///
class ReferenceEntities implements Model {
  /// The entity's stable identifier — a domain of records the catalog POINTS AT instead of duplicating, so a brand is edited once and not on nine thousand products. Unique per tenant.
  final String? code;

  /// When the row was created. Server-set — it is not part of any request body.
  final String? created_at;

  /// The row's own id, generated by the database. A client never sends one; it reads one back and uses it in the path of every later call.
  final String? id;

  /// A delivery path or URL for the entity's own icon. Cosmetic — nothing in this app resolves it.
  final String? image;

  /// What the entity is called, per language tag — the heading over its record list.
  final Map? labels;

  /// When the row was last written. Server-set — it is not part of any request body.
  final String? updated_at;

  ReferenceEntities({
    this.code,
    this.created_at,
    this.id,
    this.image,
    this.labels,
    this.updated_at,
  });

  factory ReferenceEntities.fromMap(Map<String, dynamic> map) {
    return ReferenceEntities(
      code: map['code']?.toString(),
      created_at: map['created_at']?.toString(),
      id: map['id']?.toString(),
      image: map['image']?.toString(),
      labels: map['labels'],
      updated_at: map['updated_at']?.toString(),
    );
  }

  @override
  Map<String, dynamic> toMap() {
    return {
      "code": code,
      "created_at": created_at,
      "id": id,
      "image": image,
      "labels": labels,
      "updated_at": updated_at,
    };
  }
}
