part of '../../models.dart';

/// 
class Reservation implements Model {
    /// When the row was created. Server-set: it is in no request body, and a value sent for it is ignored.
    final String? created_at;

    /// When this hold lapses. The sweeper — POST /inventories/reservations/sweep, and the 'expire-reservations' schedule that runs it every 15 minutes — releases everything past this moment exactly as a cancellation would, so an abandoned checkout stops holding stock on its own. Null means the row named no deadline: it is swept on its AGE instead once `reservation_ttl_minutes` is above 0, which is what makes turning that setting on retroactive.
    final String? expires_at;

    /// The row's own id, generated by the database. A caller never sends one — it reads one back and puts it in the path of every later call.
    final String? id;

    /// Which location is holding the goods for this order. Chosen at reserve time by the tenant's `allocation_strategy` — not by the caller, unless `ship_to.location_code` names one and the strategy is 'nearest'.
    final String? location_id;

    /// Free-form, and one key this app writes itself: `backordered` — how much of this hold was not covered by stock on hand when it was taken. Absent on a hold that was fully covered.
    final Map<String, dynamic>? metadata;

    /// The order this hold belongs to. The caller supplies it — this app mints nothing — and it is the handle POST /inventories/release and POST /inventories/commit act on, so it has to be the same string the order carries elsewhere. At least one character (CHECK `length(order_ref) > 0`). Not unique: an order holds one reservation per item, and they are released or committed together.
    final String? order_ref;

    /// The product being held, copied from the reserve call. Null when the item was identified by SKU.
    final String? product_id;

    /// How much is being held, ALWAYS POSITIVE — the database CHECK is `quantity > 0`, because a hold of nothing is not a hold. It is added to `stock_levels.reserved` while the status is `active` and taken off again when the hold is released, expires or is committed. The matching ledger booking carries the same number NEGATIVE (see `stock_movements.quantity`).
    final double? quantity;

    /// The article number being held, copied from the reserve call. Null when the item was identified by product id.
    final String? sku;

    /// Where the hold stands in the reserve → commit | release lifecycle. 'active' — holding stock, and the ONLY status counted in `stock_levels.reserved`. 'committed' — the order shipped, so `on_hand` and `reserved` both fell. 'released' — the hold was given back, by POST /inventories/release or by the expiry sweeper. Both end states are final: nothing in this app moves a reservation back to active.
    final enums.ReservationStatus? status;

    /// The tenant this row belongs to, as a slug. Set by the platform, never by a caller — it is the row-level security scope, not a field, and every row a request can reach is inside it already.
    final String? tenant_id;

    /// When the hold last changed — in practice, when it moved out of `active`.
    final String? updated_at;

    Reservation({
        this.created_at,
        this.expires_at,
        this.id,
        this.location_id,
        this.metadata,
        this.order_ref,
        this.product_id,
        this.quantity,
        this.sku,
        this.status,
        this.tenant_id,
        this.updated_at,
    });

    factory Reservation.fromMap(Map<String, dynamic> map) {
        return Reservation(
            created_at: map['created_at']?.toString(),
            expires_at: map['expires_at']?.toString(),
            id: map['id']?.toString(),
            location_id: map['location_id']?.toString(),
            metadata: map['metadata'],
            order_ref: map['order_ref']?.toString(),
            product_id: map['product_id']?.toString(),
            quantity: map['quantity']?.toDouble(),
            sku: map['sku']?.toString(),
            status: map['status'] != null ? enums.ReservationStatus.values.firstWhere((e) => e.value == map['status']) : null,
            tenant_id: map['tenant_id']?.toString(),
            updated_at: map['updated_at']?.toString(),
        );
    }

    @override
    Map<String, dynamic> toMap() {
        return {
            "created_at": created_at,
            "expires_at": expires_at,
            "id": id,
            "location_id": location_id,
            "metadata": metadata,
            "order_ref": order_ref,
            "product_id": product_id,
            "quantity": quantity,
            "sku": sku,
            "status": status?.value,
            "tenant_id": tenant_id,
            "updated_at": updated_at,
        };
    }
}
